# Stage 1: Compilar la aplicación Angular
FROM node:14 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build -- --outputPath=./dist/digital-experts-web

# Stage 2: Servir la aplicación con Nginx
FROM nginx:alpine
COPY --from=build-stage /app/dist/digital-experts-web/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
